-- liquibase formatted sql

-- changeSet Danil:4
create table flight_request(
      id int generated by default as identity primary key,
      origin varchar(100),
      destination varchar(100),
      departure_at date,
      return_at date,
      created_at date,
      person_id int references person(id)
);
-- rollback drop table flight_request;