-- liquibase formatted sql

-- changeSet Danil:1
create table person(
    id int generated by default as identity primary key,
    username varchar(100) unique,
    email varchar(100) unique,
    password varchar(100)
);
-- rollback drop table person;