-- liquibase formatted sql

-- changeSet Danil:3
create table train_request(
    id int generated by default as identity primary key,
    fromm varchar(100),
    too varchar(100),
    departure_at date,
    created_at date,
    person_id int references person(id)
);
-- rollback drop table train_request;